### PR TITLE
Fix issues with filters by Date Fields

### LINKED ISSUE #587: Filters not working like expected for date fields
Currently the Loupe adapter stores dates as timestamps, whereas the Elasticsearch adapter uses its native date field. Unless I'm mistaken, this means the same `Search` cannot work with both.

It would be nice to provide an abstraction for this. I suggest using PHP's `DateTimeImmutable` and converting to the required format in the `SearcherInterface` implementation. Thoughts?

### PR DESCRIPTION
**Pull request by alexander-schranz**
Filters based on `datetime` fields seems currently not work correctly in:

 - [x] Loupe (expect integer in filter)
 - [x] Typesense (expect integer in filter)
 - [x] Meilisearch (expect integer in filter, and schema as integer) (requires drop reindex)
 - [x] Algolia (expect integer in filter, and schema as integer) (requires drop reindex)
 - [x] RediSearch (expect integer in filter, and schema as integer) (requires drop reindex)
 - [x] Solr (expect specific format in filters, and in indexing) (requires drop reindex)

⚠️ `Marshaller` and `Flattenmarshaller` services also changed the `dateAsInteger: true` was removed in favor of `dateFormat: 'U'`. To allow different date formats for Example for Solr which requires a specific format. As they are still `@internal` there are no issues with BC Break here. But still a reindex is required for Solr, Redisearch and 

fixes #587

### BC Breaks

For `Meilisearch`, `Algolia`, `RediSearch` and `Solr` the saving of the date time type changed and requires a drop reindex. `cmsig:seal:reindex --drop`.

### CODE REVIEW

File: packages/seal-meilisearch-adapter/src/MeilisearchIndexer.php [hunk 1]
```diff
@@ -29,6 +29,7 @@ public function __construct(
         private readonly Client $client,
     ) {
         $this->marshaller = new Marshaller(
+            dateFormat: 'U',
```
Comment (alexander-schranz) [inline packages/seal-meilisearch-adapter/src/MeilisearchIndexer.php:32]: if I understood correctly https://www.meilisearch.com/docs/learn/filtering_and_sorting/working_with_dates

sorting works by date strings, but for filters we need save a unixtimestamp. So I use like in Loupe and Typesense a UnixTimestap now.

File: packages/seal-solr-adapter/src/SolrIndexer.php [hunk 2]
```diff
@@ -29,6 +29,7 @@ public function __construct(
         private readonly Client $client,
     ) {
         $this->marshaller = new FlattenMarshaller(
+            dateFormat: 'Y-m-d\TH:i:s\Z',
```
Comment (alexander-schranz) [inline packages/seal-solr-adapter/src/SolrIndexer.php:32]: Solr Expect a specific date format, While it did work with our `c` format it did remove the timezone incorrectly and so the filters didn't work for exact matches. We are now converting it into correct values.

File: packages/seal-algolia-adapter/src/AlgoliaSearcher.php [hunk 3]
```diff
@@ -34,6 +34,7 @@ public function __construct(
         private readonly SearchClient $client,
     ) {
         $this->marshaller = new Marshaller(
+            dateFormat: 'U',
```
Comment (alexander-schranz) [inline packages/seal-algolia-adapter/src/AlgoliaSearcher.php:37]: same as for Meilisearch the Algolia requires a unixtimestamp for filtering: https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-attributes/#filter-by-date
